import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

// Load the Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Include the subsets you need
  variable: "--font-poppins", // Define a CSS variable for the font
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Add desired font weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`} // Use Poppins variable here
      >
        <div>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
